require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:default) do |t|
  Dir.mkdir "reports" unless File.directory?("reports")
  t.profile = 'default'
end

Cucumber::Rake::Task.new(:smoke) do |t|
  t.profile = 'smoke'
end


