<% reports = "--format pretty --format html --out reports/feature_report.html --format json --out reports/feature_report.json" %>

default: BROWSER=firefox --require features <%= reports %> --tags ~@wip
wip:     BROWSER=firefox --require features <%= reports %> --tags @wip

